#!/bin/bash

RUBY="2.4"

cd ~/

# Upgrade AWS-CLI
sudo pip install --upgrade awscli

# Allow installing Node.js
curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -

# Install dependencies with Yum
sudo yum -y update
sudo yum -y groupinstall "Development Tools"
sudo yum -y install git-core jq nodejs openssl-devel readline-devel

# Install rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
rbenv install 2.5.1
ruby global 2.5.1
~/.rbenv/bin/rbenv init

# Install Bundler
gem install bundler

# Install jwt & octokit for communicating with GitHub
gem install jwt octokit

# Install rbspy
mkdir ~/rbspy
pushd ~/rbspy
curl -L https://github.com/rbspy/rbspy/releases/download/v0.2.10/rbspy-v0.2.10-x86_64-unknown-linux-musl.tar.gz > rbspy.tar.gz
tar -xvzf rbspy.tar.gz
sudo mv rbspy /usr/bin/
popd
rm -rf ~/rbspy

# Download Utterson
git clone https://github.com/jekyll/Utterson.git Utterson

# Link EC2 boot script to init.d
sudo ln Utterson/aws/ec2/boot /etc/rc.d/init.d/utterson
