#!/bin/bash

RUBY="2.4"

cd ~/

# Allow installing Node.js
curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -

# Install dependencies with Yum
sudo yum -y update
sudo yum -y install git jq nodejs

# Install RVM
gpg --batch --list-keys # Initialize ~/.gnupg/
gpg --batch --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable
source .rvm/scripts/rvm
rvm install "$RUBY"
rvm use     "$RUBY" --default
# In order to use RVM outside of this script, the user will either need to
# logout and login again, or run `source ~/.rvm/scripts/rvm` in the shell

# Install Bundler
gem install bundler

# Install jwt
gem install jwt

# Download Utterson
git clone https://github.com/jekyll/Utterson.git Utterson

# Link EC2 boot script to init.d
sudo ln Utterson/aws/ec2/boot /etc/rc.d/init.d/utterson
