#!/bin/bash

# Install dependencies with Yum
sudo yum -y update
sudo yum -y install git jq

# Install RVM
gpg --batch --list-keys # Initialize ~/.gnupg/
gpg --batch --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
rvm install 2.4

# Install Bundler
gem install bundler

# Download Utterson
git clone https://github.com/jekyll/Utterson.git

# Link EC2 boot script to init.d
sudo ln ~/Utterson/aws/ec2/boot /etc/rc.d/init.d/utterson
