require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - sites/**/*
    - vendor/**/*
    - Gemfile

Jekyll/NoPutsAllowed:
  Enabled: false
