#!/usr/bin/env bash
set -e
ulimit -t 1200

export BUNDLE_GEMFILE="$(pwd)/Gemfile"
bundle update

NUMBER_OF_RUNS=3
RESULTS="$(pwd)/results.csv"
if [[ ! -s $RESULTS ]]; then
	echo "Jekyll version, percent of CPU this job got, user time in seconds, elapsed real time (wall clock) in seconds, site" > $RESULTS
fi

if [[ -n $REF ]]; then
	VERSION=$REF
elif [[ -n $PR ]]; then
	VERSION=$PR
else
	VERSION="unspecified"
fi

if command -v gtime; then
	TIME=$(which gtime)
else
	TIME=$(which time)
fi

# Create tmp/ directory
TMPDIR="$(pwd)/sites"
if [[ -d $TMPDIR ]]; then
	rm -rf "$TMPDIR"
fi
mkdir -p "$TMPDIR/source"
mkdir -p "$TMPDIR/destination"

for SITE in $(cat "site-list"); do
	SOURCE="$TMPDIR/source/$(md5 <<< $SITE)"
	DESTINATION=${SOURCE/source/destination}
	if [[ ! -d $SOURCE ]]; then
		git clone --recurse-submodules -q "$SITE" "$SOURCE"
	fi
	for ((i=0; i<NUMBER_OF_RUNS; ++i)); do
		"$TIME" -ao "$RESULTS" -f"$VERSION,%P,%U,%e,$SITE" \
			bundle exec jekyll build -s "$SOURCE" -d "$DESTINATION" --trace
	done
done
