#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "yaml"

def linkify_pr(text, repo)
  "[##{text}](#{File.join(repo, "pull", text)})"
end

def linkify_sha(ref, repo)
  "[`#{ref[0...7]}`](#{File.join(repo, "commit", ref)})"
end

def linkify_flamegraph(site)
  site = site.split("/").last
  "[&#x1f525;&#xfe0f;](https://utterson.pathawks.com/#{ENV["REF"]}/#{site}.svg)"
end

def linkify_site(site)
  "[#{site.split("/").last}](#{site})"
end

def markdown_header
  repo_url = ENV.fetch("HTML_URL", "https://github.com/jekyll/jekyll")
  ref = ENV["REF"]
  pr = ENV["PR"]
  frontmatter = {
    "PR"        => pr,
    "REF"       => ref,
    "title"     => "Performance Check",
    "permalink" => "/#{ref}.html",
  }
  <<~HEADER
    #{frontmatter.to_yaml}---

    The following report was generated for PR #{linkify_pr(pr, repo_url)},
    on commit #{linkify_sha(ref, repo_url)}

  HEADER
end

results = CSV.table("results.csv")

puts markdown_header if ENV.key?("REF") && ENV.key?("PR")

puts "| ref                                      | build time in seconds |"
puts "|:-----------------------------------------|----------------------:|"

summed_results = {}
site_results = {}
results.each do |row|
  summed_results[row[0]] = 0.0 unless summed_results.key?(row[0])
  site_results[row[2]] ||= [linkify_flamegraph(row[2]), linkify_site(row[2]), 0.0]
  summed_results[row[0]] += row[1]
  site_results[row[2]][2] += row[1] if row[0] == "##{ENV["PR"]}"
end

summed_results.each do |ref, time|
  ref = "`#{ref}`" unless ref =~ %r!\A(?:[0-9a-f]+|#\d+)\Z!
  puts format("| %-40s | %21.2f |", ref, time)
end

if ENV.key?("REF") && ENV.key?("PR")
  puts <<~HEADER

    |  | site | total build time in seconds |
    |--|:-----|----------------------------:|
  HEADER
  site_results.values.each do |data|
    puts "| #{data.join(" | ")} |"
  end
end
