#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "yaml"

def linkify_pr(text, repo)
  "[##{text}](#{File.join(repo, "pull", text)})"
end

def linkify_sha(pretty_ref, full_ref, repo)
  "[`#{pretty_ref}`](#{File.join(repo, "commit", full_ref)})"
end

results = CSV.table("results.csv")

if ENV.key?("REF") && ENV.key?("PR")
  repo_url = ENV.fetch("URL")
  pretty_ref = ENV.fetch("REF")[0...7]
  frontmatter = {
    "PR"        => ENV.fetch("PR"),
    "REF"       => pretty_ref,
    "title"     => "Performance Check",
    "permalink" => "/#{ENV.fetch "REF"}.html",
  }
  puts <<~HEADER
    #{frontmatter.to_yaml}---

    The following report was generated for PR #{linkify_pr(frontmatter["PR"], repo_url)},
    on commit #{linkify_sha(pretty_ref, ENV.fetch("REF"), repo_url)}

  HEADER
end

puts "| ref                                      | build time in seconds |"
puts "|:-----------------------------------------|----------------------:|"

summed_results = {}
results.each do |row|
  summed_results[row[0]] = 0.0 unless summed_results.key?(row[0])
  summed_results[row[0]] += row[1]
end

summed_results.each do |ref, time|
  ref = "`#{ref}`" unless ref =~ %r!\A(?:[0-9a-f]+|#\d+)\Z!
  puts format("| %-40s | %21.2f |", ref, time)
end
