#!/bin/bash
# set -e

# Builds a PR based on a message received from SQS

QUEUE_URL="https://sqs.us-east-1.amazonaws.com/631571985519/utterson.fifo"

JSON_RESPONSE=$(aws sqs receive-message --queue-url "$QUEUE_URL" --message-attribute-names All)

read -d "###" -a BUILDS <<< $(jq -r '.Messages[0].MessageAttributes.base.StringValue,.Messages[0].MessageAttributes.pr.StringValue' <<< $JSON_RESPONSE)
RECEIPT_HANDLE=$(jq -r '.Messages[0].ReceiptHandle' <<< $JSON_RESPONSE)

if [[ -f results.csv ]]; then
	rm results.csv
fi

REF="${BUILDS[0]}" ./bench
 PR="${BUILDS[1]}" ./bench
./report

aws sqs delete-message --receipt-handle "$RECEIPT_HANDLE" --queue-url "$QUEUE_URL"
