#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "net/http"
require "uri"
require "date"

token = File.expand_path("../token", __dir__)
report = File.expand_path("../../report", __dir__)

date = Time.now.strftime("%Y-%m-%dT%H:%M:%SZ")

json = JSON(
  :name         => "Performance Check",
  :status       => "completed",
  :conclusion   => "success",
  :completed_at => date,
  :details_url  => "https://utterson.pathawks.com/#{ENV["HEAD_SHA"]}.html",
  :head_branch  => ENV["HEAD_BRANCH"],
  :head_sha     => ENV["HEAD_SHA"],
  :started_at   => ENV.fetch("STARTED_AT", date),
  :output       => {
    :title   => "Build Complete",
    :summary => "The build completed",
    :text    => `#{report}`,
  }
)

uri = URI("#{ENV["URL"]}/check-runs")
req = Net::HTTP::Post.new(uri)
req["Authorization"] = "token #{`#{token}`.chomp}"
req["Accept"] = "application/vnd.github.antiope-preview+json"
req.body = json

http = Net::HTTP.new(uri.hostname, uri.port)
http.use_ssl = (uri.scheme == "https")
http.request(req)
