#!/bin/bash

DATE=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
REPORT=$(./report)
REPORT="${REPORT//
/\n}"
TOKEN="$(./github/token)"

JSON='{"name":"Performance Check", "head_branch":"'$BRANCH'", "head_sha":"'$HEAD'", "status":"completed", "conclusion":"success", "completed_at":"'$DATE'", "output":{"title":"Build Complete", "summary":"The build completed", "text":"'"$REPORT"'"}}'

echo "$JSON"

curl -i -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.antiope-preview+json" -d "$JSON" "$URL/check-runs"
