#!/bin/bash

DATE=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
TOKEN="$(./github/token)"

JSON='
{
	"name": "Performance Check",
	"head_branch": "'$BRANCH'",
	"head_sha": "'$HEAD'",
	"status": "in_progress",
	"started_at": "'$DATE'"
}'

curl -i -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.antiope-preview+json" -d "$JSON" "$URL/check-runs"
