#!/usr/bin/env ruby
# frozen_string_literal: true

require "English"
require "json"
require "jwt" # https://rubygems.org/gems/jwt
require "net/http"
require "openssl"
require "uri"

# Private key contents
get_secret = File.expand_path("../aws/secretsmanager/get", __dir__)
private_pem = `#{get_secret} GitHub`
exit unless $CHILD_STATUS.success?
private_key = OpenSSL::PKey::RSA.new(private_pem)

# Generate the JWT
payload = {
  # issued at time
  :iat => Time.now.to_i,
  # JWT expiration time (10 minute maximum)
  :exp => Time.now.to_i + (10 * 60),
  # GitHub App's identifier
  :iss => 13_446,
}

jwt = JWT.encode(payload, private_key, "RS256")

installation = ENV.fetch("INSTALLATION")

uri = URI("https://api.github.com/installations/#{installation}/access_tokens")
req = Net::HTTP::Post.new(uri)
req["Authorization"] = "Bearer #{jwt}"
req["Accept"] = "application/vnd.github.machine-man-preview+json"

http = Net::HTTP.new(uri.hostname, uri.port)
http.use_ssl = (uri.scheme == "https")
res = http.request(req)

json = JSON.parse(res.body)

puts json["token"]
