#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "net/http"
require "uri"

jwt = File.expand_path("jwt", __dir__)

uri = URI("https://api.github.com/installations/#{ENV["INSTALLATION"]}/access_tokens")
req = Net::HTTP::Post.new(uri)
req["Authorization"] = "Bearer #{`#{jwt}`}"
req["Accept"] = "application/vnd.github.machine-man-preview+json"

http = Net::HTTP.new(uri.hostname, uri.port)
http.use_ssl = (uri.scheme == "https")
res = http.request(req)

json = JSON.parse(res.body)

puts json["token"]
